export const ru = {
  Buyer: 'Покупатель',
  'Telegram-channel': 'Наш Telegram-канал',
  Search: 'Поиск',
  'Become-a-seller': 'Стать продавцом',
  'Discounted products': 'Товары со скидкой',
  '50%-discount': 'Скидка 50%',
  'New-Years-discounts': 'Новогодние скидки',
  'Goods-in-stock': 'Товары в наличии',
  Categories: 'Категории',
  Profile: 'Профиль',
  Chats: 'Чаты',
  'Add-product': 'Добавить товар',
  'Want-to-buy': 'Хочу купить',
  Favorites: 'Избранное',
  Filter: 'Фильтр',
  Catalog: 'Каталог',
  'View-all': 'Посмотреть всё',
  Buy: 'Купить',
  Electronics: 'Электроника',
  Appliances: 'Бытовая техника',
  Consoles: 'Консоли',
  Games: 'Игры',
  Food: 'Продукты питания',
  'Household-goods': 'Бытовые товары',
  'Computer-goods': 'Компьютерные товары',
  'Headphones-and-audio-equipment': 'Наушники и аудиотехника',
  Cloth: 'Одежда',
};
