export const uz = {
  Buyer: 'Xaridor',
  'Telegram-channel': 'Telegram kanalimiz',
  Search: 'Qidirmoq',
  'Become-a-seller': 'Sotuvchiga aylaning',
  'Discounted products': 'Chegirmali mahsulotlar',
  '50%-discount': '50% chegirma',
  'New-Years-discounts': 'Yangi yil chegirmalari',
  'Goods-in-stock': 'Stokdagi mahsulotlar',
  Categories: 'Kategoriyalar',
  Profile: 'Profil',
  Chats: 'Suhbatlar',
  'Add-product': "Mahsulot qo'shing",
  'Want-to-buy': 'Sotib olmoqchi',
  Favorites: 'Sevimlilar',
  Filter: 'Filtr',
  Catalog: 'Katalog',
  'View-all': "Hammasini ko'rish",
  Buy: 'Sotib olish',
  Electronics: 'Elektronika',
  Appliances: 'Maishiy texnika',
  Consoles: 'Konsollar',
  Games: "O'yinlar",
  Food: 'Oziq-ovqat maxsulotlari',
  'Household-goods': "Uy-ro'zg'or buyumlari",
  'Computer-goods': 'Kompyuter tovarlari',
  'Headphones-and-audio-equipment': 'Naushniklar va audio uskunalar',
  Cloth: 'Mato',
};
